import aron
import bulbasaur
import charmander
import chikorita
import cubone
import cydaquil
import eevee
import exeggcute
import geodude
import machop
import magnemite
import meowth
import minun
import mudkip
import nidoran
import pidgey
import pikachu
import plusle
import poochyena
import psyduck
import rattata
import skitty
import squirtle
import sunkern
import torchic
import totodile
import treecko
import voltorb
import weedle
import wurmple
import zapdos
import zigzagoon